"""
User

This module defines the User SQLAlchemy model, representing a registered
user of the CinéMood application.

It covers authentication data, profile information, and streaming platform
preferences. Passwords are never stored in plain text - hashing is handled
by the authentication service before this model is populated.
"""

from app.database import Base
from app.models.base_model import BaseModel
from app.models.platform import Platform
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import Table, Column, ForeignKey, String, Boolean, Integer
from typing import Optional
import bcrypt

user_platforms = Table(
    "user_platforms",
    Base.metadata,
    Column("user_id", ForeignKey("users.id"), primary_key=True),
    Column("platform_id", ForeignKey("platforms.id"), primary_key=True),
)


class User(BaseModel):
    """
    SQLAlchemy model representing a registered CinéMood user.

    Inherits from BaseModel, which provides:
        - id (UUID primary key, generated by PostgreSQL)
        - created_at (timestamp, set at insertion)
        - updated_at (timestamp, refreshed on every update)

    Attributes:
        first_name (str): User's first name. Maximum 60 characters.
        last_name (str): User's last name. Maximum 60 characters.
        username (str): Display name, generated from first_name + last_name
            at registration. Maximum 120 characters. Modification planned
            as a post-MVP feature (see Won't Have).
        email (str): Unique login identifier. Maximum 255 characters.
            Uniqueness is enforced at the database level.
        hashed_password (str): bcrypt hash of the user's password.
            The plain-text password is never stored.
        is_admin (bool): Administrative flag. Defaults to False.
            Reserved for future admin features.
        age (int): Optional. Used to filter recommendations by age rating
            (US-14, Could Have).
        platforms (list[Platform]): Streaming platforms selected by the user
            on their profile. Stored in the ``user_platforms`` association
            table. Loaded eagerly (lazy="joined") so they are always
            available alongside the User without an extra query.

    Notes:
        Validation of email format and password complexity is handled
        by Pydantic schemas, not by this model.
        Password hashing is handled by the authentication service.
    """

    __tablename__ = "users"

    first_name: Mapped[str] = mapped_column(
        String(60),
        nullable=False
    )
    last_name: Mapped[str] = mapped_column(
        String(60),
        nullable=False
    )
    username: Mapped[str] = mapped_column(
        String(120),
        nullable=False
    )
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False
    )
    hashed_password: Mapped[str] = mapped_column(
        String(255),
        nullable=False
    )
    is_admin: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False
    )
    age: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True
    )
    platforms: Mapped[list["Platform"]] = relationship(
        "Platform",
        secondary=user_platforms,
        lazy="joined"
    )

    def verify_password(self, plain_password: str) -> bool:
        """
        Verify whether a provided password matches the stored hashed password.

        Uses bcrypt to safely compare the plain-text input against the hash
        stored in the database. Both values are encoded to bytes before
        comparison, as required by the bcrypt library.

        Args:
            plain_password (str): Plain-text password provided by the user
                at login.

        Returns:
            bool: True if the password matches the stored hash,
                False otherwise.
        """
        return bcrypt.checkpw(
            plain_password.encode('utf-8'),
            self.hashed_password.encode('utf-8')
        )
